env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "g6juqk/pIJTlmM+8aOAO69Pu3nze7uEifn58DtqG/9CKUlRSjnhAqG9EO7UyH1z0GnAEDj/ZRHFiAycYv9tLcFhzhOYCTiYUl4d7PwSd5vS1liDgfrQJNtdR1W2oqr+wVt8g3sReGBbgUlMrGu6fP3G8Xsv1OOj5mFR/LxVECXI="
addons:
  coverity_scan:
    project:
      name: "stepping-stone/sepiola"
      description: "Build submitted via Travis CI"
    notification_email: info@stepping-stone.ch
    build_command_prepend: "mkdir coverity; cd coverity; cmake .."
    build_command: "make"
    branch_pattern: coverity_scan
language: cpp
compiler:
  - gcc
before_install:
  - echo 'yes' | sudo add-apt-repository ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev cmake
before_script:
  - mkdir build
  - cd build
script:
  - cmake ..
  - make
